"""Migrate teacher to new table

Revision ID: 0ce4a6902d68
Revises: 78aac1b9d4fa
Create Date: 2023-11-11 11:24:03.617872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ce4a6902d68'
down_revision = '78aac1b9d4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.drop_constraint('classes_subjects_ibfk_3', type_='foreignkey')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', mysql.VARCHAR(length=32), nullable=True))
        batch_op.create_foreign_key('classes_subjects_ibfk_3', 'users', ['teacher'], ['id'])

    # ### end Alembic commands ###
