"""Add unique to teacher phone nr

Revision ID: 1489576f0111
Revises: d5c1f3c3b117
Create Date: 2024-02-23 10:44:43.686062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1489576f0111'
down_revision = 'd5c1f3c3b117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['contact'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
