"""Add title column to Summary

Revision ID: 23b48c5c87e4
Revises: 4610ec2546c0
Create Date: 2023-11-10 19:17:55.681628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b48c5c87e4'
down_revision = '4610ec2546c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
