"""Add date to Classroom table

Revision ID: 2852e31ac694
Revises: 97855f5035d7
Create Date: 2023-11-13 11:34:15.468119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2852e31ac694'
down_revision = '97855f5035d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.Date(), nullable=True))
        batch_op.alter_column('begin',
               existing_type=sa.DATE(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('end',
               existing_type=sa.DATE(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=sa.Time(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('begin',
               existing_type=sa.Time(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('day')

    # ### end Alembic commands ###
