"""Remove state from classrooms table

Revision ID: 34512c05f922
Revises: 68d78923eddd
Create Date: 2024-02-04 12:54:33.883954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34512c05f922'
down_revision = '68d78923eddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
