"""Fix(Table): Add unique constraint to classes_subjects

Revision ID: 39a7c072ad62
Revises: 820ccb7a1015
Create Date: 2024-01-29 14:49:21.967908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a7c072ad62'
down_revision = '820ccb7a1015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['subject_id', 'class_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
