"""Add is_deleted field to some tables

Revision ID: 42620c206ff0
Revises: cf7521fec599
Create Date: 2024-01-11 11:56:48.947407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42620c206ff0'
down_revision = 'cf7521fec599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('teachers_cs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_cs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
