"""Remove ON DELETE CASCADE from Parents Relationship

Revision ID: 449753808c08
Revises: 388c2b904d10
Create Date: 2023-12-22 11:01:14.741063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449753808c08'
down_revision = '388c2b904d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'parents', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_ibfk_1', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
