"""update users

Revision ID: 5ca1497e2393
Revises: 
Create Date: 2023-09-11 14:17:22.336771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ca1497e2393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=15), nullable=True))
        batch_op.drop_column('token')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('estado')
        batch_op.drop_column('criado')

    # ### end Alembic commands ###
