"""New table: Absences

Revision ID: 68d78923eddd
Revises: b4b915241360
Create Date: 2024-02-04 12:44:05.092315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d78923eddd'
down_revision = 'b4b915241360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('presence', sa.Boolean(), nullable=True),
    sa.Column('material', sa.Boolean(), nullable=True),
    sa.Column('late', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absences')
    # ### end Alembic commands ###
