"""Change head_teacher ondelete action

Revision ID: 7d0078a9baa0
Revises: 42620c206ff0
Create Date: 2024-01-20 13:50:36.933288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0078a9baa0'
down_revision = '42620c206ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('classes_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['head_teacher'], ['teacher_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('classes_ibfk_2', 'teachers', ['head_teacher'], ['teacher_id'])

    # ### end Alembic commands ###
