"""Add is_deleted field to teachers

Revision ID: 820ccb7a1015
Revises: 7d0078a9baa0
Create Date: 2024-01-25 17:16:29.402603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820ccb7a1015'
down_revision = '7d0078a9baa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
