"""Fix absences unique key

Revision ID: 8932524c302b
Revises: a1f773b6eb1b
Create Date: 2024-02-07 18:15:54.992287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8932524c302b'
down_revision = 'a1f773b6eb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_index('classroom_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_index('classroom_id', ['classroom_id'], unique=True)

    # ### end Alembic commands ###
