"""Unique keys on Teacher_CS

Revision ID: 92c3a761c12a
Revises: 98d849d4c744
Create Date: 2023-11-12 13:15:27.554799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c3a761c12a'
down_revision = '98d849d4c744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_cs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['teacher', 'csid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_cs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
