"""Fixed Models 2

Revision ID: 9533dd7521ce
Revises: d55ede5f951f
Create Date: 2023-11-10 14:22:59.194821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9533dd7521ce'
down_revision = 'd55ede5f951f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.drop_constraint('classes_subjects_ibfk_2', type_='foreignkey')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('classes_subjects_ibfk_2', 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###
