"""Fix last migration

Revision ID: 98d849d4c744
Revises: 0ce4a6902d68
Create Date: 2023-11-11 11:27:55.806495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d849d4c744'
down_revision = '0ce4a6902d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_cs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['teacher'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers_cs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###
