"""Fix absences

Revision ID: a1f773b6eb1b
Revises: 293dfabe77b4
Create Date: 2024-02-07 18:07:13.733983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f773b6eb1b'
down_revision = '293dfabe77b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_index('classroom_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_index('classroom_id', ['classroom_id'], unique=True)

    # ### end Alembic commands ###
