"""Add Classrooms Table

Revision ID: a309fbb688dd
Revises: 92c3a761c12a
Create Date: 2023-11-12 15:15:44.977734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a309fbb688dd'
down_revision = '92c3a761c12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint('summaries_ibfk_1', type_='foreignkey')
        batch_op.drop_column('csid')
        batch_op.drop_column('end')
        batch_op.drop_column('state')
        batch_op.drop_column('begin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('begin', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('end', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('csid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('summaries_ibfk_1', 'classes_subjects', ['csid'], ['id'])

    # ### end Alembic commands ###
