"""AdRemove title from summaries

Revision ID: b4b915241360
Revises: c73de06c39fe
Create Date: 2024-02-03 15:25:01.343216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4b915241360'
down_revision = 'c73de06c39fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
