"""alter absence.user_id to ondelete cascade

Revision ID: bd1fa1a36f0c
Revises: dc2777632d39
Create Date: 2024-02-23 12:23:19.857591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1fa1a36f0c'
down_revision = 'dc2777632d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_constraint('absences_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('absences_ibfk_2', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
