"""Add unique constraint to summary classroom_id

Revision ID: c73de06c39fe
Revises: 39a7c072ad62
Create Date: 2024-02-03 14:37:30.609917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73de06c39fe'
down_revision = '39a7c072ad62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['classroom_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
