"""Fixed Models

Revision ID: d55ede5f951f
Revises: b76057c96cb0
Create Date: 2023-11-10 14:11:18.607836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd55ede5f951f'
down_revision = 'b76057c96cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.drop_index('id')
        batch_op.drop_constraint('classes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_types', ['type_id'], ['id'])
        batch_op.drop_column('type')

    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.String(length=32), nullable=True))
        batch_op.alter_column('state',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('id')
        batch_op.create_foreign_key(None, 'users', ['teacher'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_types', ['type'], ['id'])
        batch_op.drop_column('criado')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('criado', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type')
        batch_op.drop_column('state')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('id', ['id'], unique=False)
        batch_op.alter_column('state',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.drop_column('teacher')

    with op.batch_alter_table('classes_subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('class_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('classes_ibfk_1', 'class_types', ['type'], ['id'])
        batch_op.create_index('id', ['id'], unique=False)
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
