"""update users2

Revision ID: e026073d2984
Revises: 5ca1497e2393
Create Date: 2023-09-11 15:26:43.364020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e026073d2984'
down_revision = '5ca1497e2393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimoLogin', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ultimoLogin')

    # ### end Alembic commands ###
