"""Fix relationship

Revision ID: e2b5d8270afb
Revises: 449753808c08
Create Date: 2023-12-23 13:31:17.900942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b5d8270afb'
down_revision = '449753808c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_ibfk_3', 'classes', ['class_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
