"""Add teacher to Classes_Subjects Table

Revision ID: fae53fea06c8
Revises: 23b48c5c87e4
Create Date: 2023-11-10 23:17:18.663624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fae53fea06c8'
down_revision = '23b48c5c87e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint('summaries_ibfk_2', type_='foreignkey')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', mysql.VARCHAR(length=32), nullable=True))
        batch_op.create_foreign_key('summaries_ibfk_2', 'users', ['teacher'], ['id'])

    # ### end Alembic commands ###
